# fly.toml app configuration file generated for server-linear-regression on 2024-06-03T18:02:07+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-linear-regression'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
